version: '3'
services:
  web:
    image: nginx
    container_name: servicio1
    ports:
      - "8080:80"
    networks:
      red1:

  php:
    image: phpmyadmin
    container_name: servicio2
    ports:
      - "8081:80"
    networks:
      red1:

  apache:
    image: apache
    container_name: servicio3
    ports:
      - "8082:80"

  python1:
    build:
      context: "./servidor1"
      dockerfile: Dockerfile
    container_name: servicio4
    ports:
      - "5001:5000"
    volumes:
      - ./datos:/app/data

  python2:
    build:
      context: "./servidor2"
      dockerfile: Dockerfile
    container_name: servicio5
    ports:
      - "5002:5000"
    volumes:
      - ./datos:/app/data

networks:
  red1:
volumes:
  datos:
